<<<<<<< HEAD
title: Xubo Lv 
description: Here is presentation for my projects
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
=======
theme: jekyll-theme-cayman
title: [FUCK]
description: [MY FRONT PAGE]
>>>>>>> 2fa455847fb8397afd42d06a72d1ec56cf791a39
